### ISSUE TITLE
Webkit2-GTK-Devel Port

### ISSUE THREAD

**Issue by jmercouris** [kencu/myports#1]
Hi, I'm trying to install your version of the webkit2-gtk-devel port because it is 2.23, and I need 2.22 for some feature dependencies in my application.

I've cloned your ports into the directory on my machine:

`/Users/jmercouris/User/ports`

I've then set up `/opt/local/etc/macports/sources.conf`

with the following contents:

```
file:///Users/jmercouris/User/ports
rsync://rsync.macports.org/release/tarballs/ports.tar [default]
```

I then execute:
`sudo port selfupdate`

I then execute
`sudo port install webkit2-gtk-devel` and am met with the following error:

```
--->  Configuring p5.24-xml-parser
Error: p5.24-xml-parser has been replaced by p5.26-xml-parser; please install that instead.
Error: Failed to configure p5.24-xml-parser: obsolete port
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_perl_p5-graveyard/p5.24-xml-parser/main.log for details.
Error: Problem while installing p5.24-xml-parser
Error: Unable to execute port: upgrade gstreamer1-gst-plugins-bad failed
```
I've attached the contents of the main.log file.

thanks for any help!

[main.log](https://github.com/kencu/myports/files/3116139/main.log)

**Comment by jmercouris** [comment]
Update: I've found that deleting pulseaudio works and remedies this issue by fetching the pulse audio port file from the rsync source. However, when I try to compile anything with Webkit2GTK I still have issues, I am trying to compile the following:

https://github.com/atlas-engineer/next

I'm simply invoking `make gtk-webkit` which compiles just fine on Linux with gtk-webkit.

[compilation.txt](https://github.com/kencu/myports/files/3116407/compilation.txt)

Any help would be greatly appreciated, thank you!

**Comment by Ambrevar** [comment]
- Gstreamer issue: it's telling you that p5.24-xml-parser is out of date,
so you might have to update this port.

- Webkit gtk issue: From the log you've posted

```
/opt/local/include/webkitgtk-4.0/JavaScriptCore/JSValueRef.h:54:18: error: missing ',' between enumerators
    kJSTypeSymbol JSC_API_AVAILABLE(macosx(JSC_MAC_TBA), ios(JSC_IOS_TBA))
```

This "JSValue" things are new in WebkitGTK 2.22.  I suspect
that a patch for an old webkitgtk is wrongly applied here.

Also why is the path `.../webkitgtk-4.0/...`?  Where does that 4.0 come from?

**Comment by jmercouris** [comment]
Update:

I ended up having to modify the patch to get it to work. Attached you'll find my modifications.


[PR-157574.txt](https://github.com/kencu/myports/files/3117106/PR-157574.txt)

**Comment by kencu** [comment]
Thanks guys. This old branch is out of date, and I upgraded the webkit2-gtk port to current versions on MacPorts over the past while. I'll delete this old relic here to avoid confusion. Sorry I missed the messages -- I guess I don't have the notifications turned on...

**Comment by jmercouris** [comment]
No problem, we had this same discussion recently as well on trac since this is now part of the main MacPorts port tree :-D

thank you for your work in supporting this port!
